version: '3'
services:
  nodered:
     image: nodered/node-red
     container_name: nodered1
     ports: 
      - "1880:1880"
     volumes:
      - ./NRdata:/data

  qewd:
    build: ./qewd1
    container_name: qewd2
    ports:
      - "3030:8080"